baseurl = "/"
languageCode = "en-us"
title = "eyeson JavaScript Library"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[markup]
  [markup.highlight]
    codeFences = false

[params]
	# General information
	author = "eyeson Team"
	description = "eyeson JavaScript Library"
	copyright = "eyeson GmbH"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/eyeson-team/js-docs"

	version = "1.8.1"
	logo = "/images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = ["eyeson.css"]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "deep-purple"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[social]
	twitter = "eyeson_team"
	github  = "eyeson-team"
	email   = "developers@eyeson.team"


[[menu.main]]
	name   = "eyeson JavaScript Library"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "Overview"
	url    = "overview/"
	weight = 20

[[menu.main]]
	name   = "Events"
	url    = "events/"
	weight = 30

[[menu.main]]
	name   = "Utilities"
	url    = "utilities/"
	weight = 40

# TODO: not ready + up-to-date
# [[menu.main]]
# 	name   = "Screen Capture"
# 	url    = "screen-capture/"
# 	weight = 40

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
